server:
  port: 9002

spring:
  application:
    name: spring-db202507
  datasource:
    url: jdbc:mariadb://localhost:3306/apiPractice
    username: root
    password: mariadb
# ?? ??? ???? db? ????? ????? ?????.

logging:
  level:
    root: INFO
    com.spring.database: DEBUG

